#!/usr/bin/python3
#
#%# family=auto
#%# capabilities=autoconf

import subprocess
import sys

if 'autoconf' in sys.argv:
    print('yes')
    sys.exit(0)
elif 'config' in sys.argv:
    print("""graph_title Ejabberd connection types
graph_args --base 1000 -l 0
graph_category ejabberd
graph_info used connection features
total.label total
total.graph no
tls.label TLS
ssl.label SSL
plain.label Unencrypted
ipv4.label IPv4
ipv6.label IPv6
compressed.label compression""")
    sys.exit(0)

p = subprocess.Popen(['ejabberdctl', 'connected_users_info'],
                     stdout=subprocess.PIPE)
stdout = p.communicate()[0].decode('utf-8').strip().split("\n")

total = len(stdout)
ipv4 = 0
ipv6 = 0
compressed = 0
tls = 0
ssl = 0
plain = 0

for line in stdout:
    jid, conn, ip, port, priority, node, uptime = line.split("\t")
    if 'tls' in conn:
        tls += 1
    elif 'ssl' in conn:
        ssl += 1
    else:
        plain += 1

    if 'compressed' in conn:
        compressed += 1
    if ip.startswith('::FFFF:'):
        ipv4 += 1
    else:
        ipv6 += 1

print("""total.value %s
tls.value %s
ssl.value %s
unencrypted.value %s
compressed.value %s
unencrypted.value %s
ipv4.value %s
ipv6.value %s""" % (total, tls, ssl, plain, compressed, ipv4, ipv6))
